# ------------------ PersistentVolume (PV) ------------------
apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  capacity:
    storage: 10Gi  # Adjust size
  accessModes:
    - ReadWriteMany  # Choose RWX, RWO, or ROX
  persistentVolumeReclaimPolicy: Retain
  storageClassName: my-storage-class
  hostPath:
    path: "/mnt/data"  # Change this for your setup

---
# ------------------ PersistentVolumeClaim (PVC) ------------------
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  accessModes:
    - ReadWriteMany  # Match PV access mode
  resources:
    requests:
      storage: 10Gi  # Request size within PV limit
  storageClassName: my-storage-class

---
# ------------------ Pod 1 ------------------
apiVersion: v1
kind: Pod
metadata:
  name: data-prep
  labels:
    app: shared
spec:
  containers:
  - name: data-prep-container
    image: alaxcia/egt309dataprep:v1
    ports:
    - containerPort: 6650

---
# ------------------ Pod 2 ------------------
apiVersion: v1
kind: Pod
metadata:
  name: model-train
  labels:
    app: shared
spec:
  containers:
  - name: model-train-container
    image: alaxcia/egt309modeltrain:v1
    ports:
    - containerPort: 6651
    volumeMounts:
    - mountPath: "/data"
      name: shared-storage
  volumes:
  - name: shared-storage
    persistentVolumeClaim:
      claimName: my-pvc

---
# ------------------ Pod 3 ------------------
apiVersion: v1
kind: Pod
metadata:
  name: model-pred
  labels:
    app: shared
spec:
  containers:
  - name: model-pred-container
    image: alaxcia/egt309modelpred:v1
    ports:
    - containerPort: 6652
    volumeMounts:
    - mountPath: "/data"
      name: shared-storage
  volumes:
  - name: shared-storage
    persistentVolumeClaim:
      claimName: my-pvc

---
# ------------------ Pod 4 ------------------
apiVersion: v1
kind: Pod
metadata:
  name: gui
  labels:
    app: shared
spec:
  containers:
  - name: gui-container
    image: alaxcia/egt309testrun:v1.2
    ports:
    - containerPort: 8080
    volumeMounts:
    - mountPath: "/data"
      name: shared-storage
  volumes:
  - name: shared-storage
    persistentVolumeClaim:
      claimName: my-pvc

---
# ------------------ Multi-Port Service ------------------
apiVersion: v1
kind: Service
metadata:
  name: multi-app-service
spec:
  sessionAffinity: ClientIP  # Sticky sessions enabled
  selector:
    app: shared  # Matches all 4 Deployments
  ports:
    - name: data-prep
      port: 6650      # External port
      targetPort: 6650  # data-prep container port
    - name: model-train
      port: 6651      # External port
      targetPort: 6651  # model-train container port
    - name: model-pred
      port: 6652
      targetPort: 6652
    - name: gui
      port: 88
      targetPort: 8080
  type: ClusterIP  # Change to NodePort or LoadBalancer if needed
